### ISSUE TITLE
Unable to make work in IE11

### ISSUE THREAD

**Issue by adeptues** [tuespetre/shadow-dom#8]
When using this in IE11 it results in the following error

`
TypeError: Invalid calling object\n   at attachShadow (http://192.168.100.38:8000/shadow-dom.js:2848:9)\n   at CDAViewer (http://192.168.100.38:8000/build/bundle.js:23:9)\n   at upgradeElement (http://192.168.100.38:8000/shadow-dom.js:664:9)\n   at tryToUpgradeElementSync (http://192.168.100.38:8000/shadow-dom.js:693:9)\n   at performInitialUpgrades (http://192.168.100.38:8000/shadow-dom.js:303:5)\n   at invokeListeners (http://192.168.100.38:8000/shadow-dom.js:3480:21)\n   at callback (http://192.168.100.38:8000/shadow-dom.js:3356:21)`

I have a promise polyfil loaded and some other IE11 ones not sure if i'm missing somthing else?

The webcomponent looks like this compiled down to es5
```typescript
export default class CDAViewer extends HTMLElement {
    private src: string;
    constructor() {
        super();
        // create the shadow dom
        let shadow = this.attachShadow({ mode: 'open' });

        //Load the template and attach ito the shadow dom
        let wrapper = document.createElement("span");
        let parser = new DOMParser();

        let node = parser.parseFromString(template.trim(), "text/xml");
        let b = node.firstChild as HTMLTemplateElement;
        //Manipulatethe shadow dom
        if (this.hasAttribute("src")) {
            this.src = this.getAttribute("src");
        }
        //set the template on the shadow dom
        wrapper.innerHTML = b.innerHTML;
        const style = this.buildCss();
        shadow.appendChild(style);
        shadow.appendChild(wrapper);
    }}
```

Specifically it looks like this is the offending code on line 2850 in shadow-dom.js the `this.namespaceURI` i not present on `this` any reason for this or what should be do to make it set?
```typescript
        if (this.namespaceURI !== 'http://www.w3.org/1999/xhtml') {
            throw _utils2.default.makeDOMException('NotSupportedError');
        }
```

upon inspecting the `this` object it appears hat namespaceURI is locked behind some IE security policy as its says permission denied in the console

**Comment by tuespetre** [comment]
Sorry I missed this issue. For some reason I was not 'watching' the repo (but now I am.) Is this something you still seek a resolution for?

**Comment by tuespetre** [comment]
Let me know if you still need any assistance. As mentioned, I am watching the repo now.
